### ISSUE TITLE
makefile missing.

### ISSUE THREAD

**Issue by yanhn** [kashimAstro/ofxAutoRiggingModel#2]
I am trying to reproduce the demo.
Could you please offer a makefile to reproduce the demo?
And is there some more tutorials? Thanks.

**Comment by kashimAstro** [comment]
you need openframeworks
to build the examples, look here:

https://openframeworks.cc/download/

configure openframeworks and compiled a basic example
and copy ofxAutoRiggingModel in the addons folder of the openframeworks branch

**Comment by yanhn** [comment]
thank you, I'll check that.
